spring.application.name=memory-app
server.port=8082

# =========================
# Ollama Configuration
# =========================
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=codellama:latest

# =========================
# Spring AI Advisor Logging
# =========================
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# =========================
# MySQL Database
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/ai_chat_memory
spring.datasource.username=root
spring.datasource.password=root

spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true